name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hongkong.aliyuncs.com
          username: 18710717157
          password: 19990109ren
      - name: Docker pull and push
        run: |
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/apiserver_receive_adapter@sha256:8c49212214efc4db3b8419357fd2e0b899a007c3af67311e61f1e25218f1ecfb
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/apiserver_receive_adapter@sha256:8c49212214efc4db3b8419357fd2e0b899a007c3af67311e61f1e25218f1ecfb registry.cn-hongkong.aliyuncs.com/atrhd/1123:knative.dev/eventing/cmd/apiserver_receive_adapter:v0.25.0
          docker push registry.cn-hongkong.aliyuncs.com/atrhd/1123:knative.dev/eventing/cmd/apiserver_receive_adapter:v0.25.0
