name: GitAlibi
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hongkong.aliyuncs.com
          username: 18710717157
          password: 19990109ren
      - name: Docker pull and push
        run: |
         
      
          docker pull gcr.io/ml-pipeline/minio
          docker tag  gcr.io/ml-pipeline/minio registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:minio-1.8.2
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:minio-1.8.2
          
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/controller@sha256:6ddffbc286a84048cfd090193d00b4ecda25a3a7bf2de1a8e873f8b3755cc913
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/controller@sha256:6ddffbc286a84048cfd090193d00b4ecda25a3a7bf2de1a8e873f8b3755cc913 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:eventing-controller
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:eventing-controller
          
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/apiserver_receive_adapter@sha256:a05b1db9acdfe901417307ddf403ec3702f219e5aeb25d692bc9542fc6421330
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/apiserver_receive_adapter@sha256:a05b1db9acdfe901417307ddf403ec3702f219e5aeb25d692bc9542fc6421330 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:apiserver_receive_adapter
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:apiserver_receive_adapter
          
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/mtping@sha256:edf462d03591e53e536640591a53538e6bea837fea15ed081eccfb42bc35a5c0
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/mtping@sha256:edf462d03591e53e536640591a53538e6bea837fea15ed081eccfb42bc35a5c0 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:dispatcher
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:dispatcher
          
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/webhook@sha256:9f70a2a8bb78781472fba0327c5d6ff91f13a29736d4502bf8ad3d60d3f16ccd
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/webhook@sha256:9f70a2a8bb78781472fba0327c5d6ff91f13a29736d4502bf8ad3d60d3f16ccd registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:eventing-webhook
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:eventing-webhook
          
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller@sha256:904f42a768a9bc64999e7302d2bc7c1c48a08e74a82355cf57be513e6a124b82
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller@sha256:904f42a768a9bc64999e7302d2bc7c1c48a08e74a82355cf57be513e6a124b82 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:imc-controller
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:imc-controller
          
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher@sha256:a6983f71c04619928199cc21e07ee6f1e1c87586621bc03b10c9ba1abd92bfa8
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher@sha256:a6983f71c04619928199cc21e07ee6f1e1c87586621bc03b10c9ba1abd92bfa8 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:channel_dispatcher
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:channel_dispatcher
          
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/broker/filter@sha256:0e25aa1613a3a1779b3f7b7f863e651e5f37520a7f6808ccad2164cc2b6a9b12
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/broker/filter@sha256:0e25aa1613a3a1779b3f7b7f863e651e5f37520a7f6808ccad2164cc2b6a9b12 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:mt-broker-filter
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:mt-broker-filter
          
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/broker/ingress@sha256:cf579f88aa2a37c240e25bb886c1ef5404e326e12c7caf571e49308612243eee
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/broker/ingress@sha256:cf579f88aa2a37c240e25bb886c1ef5404e326e12c7caf571e49308612243eee registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:mt-broker-ingress
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:mt-broker-ingress

          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/mtchannel_broker@sha256:a2678934d280ea19b0804cc7757d559a0312e2acea221b17a99bd830cd9eeaac
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/mtchannel_broker@sha256:a2678934d280ea19b0804cc7757d559a0312e2acea221b17a99bd830cd9eeaac registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:mt-broker-controller
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:mt-broker-controller
          
          docker pull gcr.io/knative-releases/knative.dev/eventing/cmd/v0.22/pingsource-cleanup@sha256:837b8d5cfe38afa297d25e7aed30ec8df80f721a084d4fdcc614d65afde4c528
          docker tag gcr.io/knative-releases/knative.dev/eventing/cmd/v0.22/pingsource-cleanup@sha256:837b8d5cfe38afa297d25e7aed30ec8df80f721a084d4fdcc614d65afde4c528 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:pingsource-cleanup
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:pingsource-cleanup
          
          docker pull gcr.io/knative-releases/knative.dev/eventing/vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate@sha256:ef150a99d5b18781746d3934f181a766b27a975cb7593d9283fbd040e9ebfe5b
          docker tag gcr.io/knative-releases/knative.dev/eventing/vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate@sha256:ef150a99d5b18781746d3934f181a766b27a975cb7593d9283fbd040e9ebfe5b registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:migrate
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:migrate
          
          docker pull gcr.io/knative-releases/knative.dev/serving/vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate@sha256:dce9002c02d7abda2f7d4b656c28029ec172d085bb116f22936cb1e096c3d1c7
          docker tag gcr.io/knative-releases/knative.dev/serving/vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate@sha256:dce9002c02d7abda2f7d4b656c28029ec172d085bb116f22936cb1e096c3d1c7 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:serving-migrate
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:serving-migrate
          
          docker pull gcr.io/knative-releases/knative.dev/net-istio/cmd/controller@sha256:ff8680da52ef47b8573ebc3393cbfa2f0f14b05c1e02232807f22699adbef57a
          docker tag gcr.io/knative-releases/knative.dev/net-istio/cmd/controller@sha256:ff8680da52ef47b8573ebc3393cbfa2f0f14b05c1e02232807f22699adbef57a registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:networking-istio
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:networking-istio
          
          docker pull gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook@sha256:1e371db6b1a9f9265fc7a55d15d98c935c0c28925ffde351fb3b93f331c5a08e
          docker tag gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook@sha256:1e371db6b1a9f9265fc7a55d15d98c935c0c28925ffde351fb3b93f331c5a08e registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:webhook
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:webhook
          
          
          docker pull gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:0b8e031170354950f3395876961452af1c62f7ab5161c9e71867392c11881962
          docker tag gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:0b8e031170354950f3395876961452af1c62f7ab5161c9e71867392c11881962 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:queue
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:queue
          
          docker pull gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256:fed92af8b9779c97482906db8857f27b5d4826708b75d0298aa30fad8900671f
          docker tag gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256:fed92af8b9779c97482906db8857f27b5d4826708b75d0298aa30fad8900671f registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:activator
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:activator
          
          docker pull gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler@sha256:bc5ae3090ab0322ed0e4f9efddb60fa85f6ff3a29156411d24d0e4764b18eba7
          docker tag gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler@sha256:bc5ae3090ab0322ed0e4f9efddb60fa85f6ff3a29156411d24d0e4764b18eba7 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:autoscaler
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:autoscaler
          
          docker pull gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:bd7c6350e5d5c4edaa197a86fb96cff78bdd3e61f33fcb77aa60930de0ec0827
          docker tag gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:bd7c6350e5d5c4edaa197a86fb96cff78bdd3e61f33fcb77aa60930de0ec0827 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:controller
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:controller
          
          docker pull gcr.io/knative-releases/knative.dev/serving/cmd/webhook@sha256:6f41d379f1aacdfbb8f6d4f539e1769040e4f01bff3ad9c249b427e54dc56ea8
          docker tag gcr.io/knative-releases/knative.dev/serving/cmd/webhook@sha256:6f41d379f1aacdfbb8f6d4f539e1769040e4f01bff3ad9c249b427e54dc56ea8 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:serving-webhook
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:serving-webhook
          
          docker pull gcr.io/arrikto/kubeflow/oidc-authservice:28c59ef
          docker tag gcr.io/arrikto/kubeflow/oidc-authservice:28c59ef registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:oidc-authservice
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:oidc-authservice
          
          
          docker pull gcr.io/arrikto/kubeflow/oidc-authservice:6ac9400
          docker tag gcr.io/arrikto/kubeflow/oidc-authservice:6ac9400 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:oidc-authservice-6ac9400
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:oidc-authservice-6ac9400
          
          docker pull gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
          docker tag gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0 registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:kube-rbac-proxy
          docker push registry.cn-hongkong.aliyuncs.com/serviceflow/kubeflowimages:kube-rbac-proxy
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
